
os : linux
dist: xenial
language : generic
jdk:
  - oraclejdk9

install: java -jar binaries/ssj.jar --build

# branch whitelist
branches:
  only:
  - master
  - gh-pages     # test the gh-pages branch
  - /pages-(.*)/ # test every branch which starts with "pages-"
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target-branch: gh-pages
  local-dir: dist
  on:
    branch: master
